version: "3.1"
services:
  database:
    image: "postgres:14"
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
      ports:
        ${PGPORT}
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
